### ISSUE TITLE
Unable to connect to Redis Sentinel serves

### ISSUE THREAD

**Issue by ludiegu** [catalyst/moodle-cachestore_redissentinel#2]
Hello, I have installed the plugin on a moodle 3.9.2 but it doesn't seem to work. The store has the following parameters:

```
Sentinel servers: 10.0.111.131,10.0.111.132,10.0.111.133
Sentinel group: sentinel
Key Prefix: (null)

```
the sentinels are reachable:

```
redis-cli -h 10.0.111.131 -p 26379
10.0.111.131:26379>
redis-cli -h 10.0.111.132 -p 26379
10.0.111.132:26379>
redis-cli -h 10.0.111.133 -p 26379
10.0.111.133:26379>
```

but still, I have the following error:

```
Unable to connect to Redis Sentinel serves: 10.0.111.131,10.0.111.132,10.0.111.133
line 145 of /cache/stores/redissentinel/lib.php: call to debugging()
line 689 of /cache/locallib.php: call to cachestore_redissentinel->__construct()
line 47 of /cache/admin.php: call to cache_administration_helper::get_store_instance_summaries()
```

Is there any further configuration I should do? Thanks!

**Comment by mrkskwsnck** [comment]
@ludiegu Did you have any luck getting it to work? I′m stuck at the very same step.

**Comment by mrkskwsnck** [comment]
Finally, I managed to get this plug-in to connect to my sentinel servers. As I assume you have received the missing `sentinel.php` file, these are the modifications I had to make (where `$sentinel` represents one IP address from the sentinel pool):

```diff
--- a/sentinel.php
+++ b/sentinel.php
@@ -48,12 +48,11 @@ class sentinel {


     private function connect($sentinel) {
+        $remote_socket = "tcp://$sentinel:26379";

         if ($this->persistent) {
-            $this->socket = @stream_socket_client($sentinel, $errorno, $errstr, $this->connecttimeout, STREAM_CLIENT_CONNECT | STREAM_CLIENT_PERSISTENT);
+            $this->socket = @stream_socket_client($remote_socket, $errorno, $errstr, $this->connecttimeout, STREAM_CLIENT_CONNECT | STREAM_CLIENT_PERSISTENT);
         } else {
-            $this->socket = @stream_socket_client($sentinel, $errorno, $errstr, $this->connecttimeout);
+            $this->socket = @stream_socket_client($remote_socket, $errorno, $errstr, $this->connecttimeout);
         }

         if (!$this->socket) {
```

**Comment by mrkskwsnck** [comment]
Finally, I got this plug-in to connect to my sentinel servers. The problem was just poor documentation.—As I was digging through the code (a.k.a. debugging) it came to me: One simply need to provide the server list along with the port number -_-

@ludiegu In your case it would be like that:

```
Sentinel servers: 10.0.111.131:26379,10.0.111.132:26379,10.0.111.133:26379
Sentinel group: sentinel
Key Prefix: (null)
```

**Comment by danmarsden** [comment]
Thanks to some improved documentation from @mrkskwsnck this should be easier to use - please create a new issue if you have any other problems!
